// <auto-generated />
using System;
using LucLopTatMei.MyAirport.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LucLopTatMei.MyAirport.EF.Migrations
{
    [DbContext(typeof(MyAirportContext))]
    partial class MyAirportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LucLopTatMei.MyAirport.EF.Bagage", b =>
                {
                    b.Property<int>("BagageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Classe")
                        .HasColumnType("char(1)");

                    b.Property<string>("CodeIata")
                        .HasColumnType("char(12)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Escale")
                        .HasColumnType("char(3)");

                    b.Property<bool?>("Prioritaire")
                        .HasColumnType("bit");

                    b.Property<string>("Ssur")
                        .HasColumnType("char(3)");

                    b.Property<string>("Sta")
                        .HasColumnType("char(1)");

                    b.Property<int?>("VolID")
                        .HasColumnType("int");

                    b.HasKey("BagageID");

                    b.HasIndex("VolID");

                    b.ToTable("Bagages");
                });

            modelBuilder.Entity("LucLopTatMei.MyAirport.EF.Vol", b =>
                {
                    b.Property<int>("VolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cie")
                        .HasColumnType("char(10)");

                    b.Property<string>("Des")
                        .HasColumnType("char(3)");

                    b.Property<DateTime>("Dhc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imm")
                        .HasColumnType("char(6)");

                    b.Property<string>("Lig")
                        .HasColumnType("char(5)");

                    b.Property<short?>("Pax")
                        .HasColumnType("smallint");

                    b.Property<string>("Pkg")
                        .HasColumnType("char(3)");

                    b.HasKey("VolID");

                    b.ToTable("Vols");
                });

            modelBuilder.Entity("LucLopTatMei.MyAirport.EF.Bagage", b =>
                {
                    b.HasOne("LucLopTatMei.MyAirport.EF.Vol", "Vol")
                        .WithMany("Bagages")
                        .HasForeignKey("VolID");
                });
#pragma warning restore 612, 618
        }
    }
}
